// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgL7xPMQn7iGjySfhxW7Aef5bVPWvcLtk',
    appId: '1:374997485934:web:1df6c248ca46da494d997f',
    messagingSenderId: '374997485934',
    projectId: 'chat-app-8332b',
    authDomain: 'chat-app-8332b.firebaseapp.com',
    storageBucket: 'chat-app-8332b.appspot.com',
    measurementId: 'G-5CC2TTECQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PIs7E4frvOSiQ_gX0idGF7u6N2i1tKI',
    appId: '1:374997485934:android:b9e9689109dfa3494d997f',
    messagingSenderId: '374997485934',
    projectId: 'chat-app-8332b',
    storageBucket: 'chat-app-8332b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7YypzaSXzNXEUYhgpa9n4nV_ZpnJtG4',
    appId: '1:374997485934:ios:99ff42679def02ea4d997f',
    messagingSenderId: '374997485934',
    projectId: 'chat-app-8332b',
    storageBucket: 'chat-app-8332b.appspot.com',
    iosClientId: '374997485934-4o0cvia7ak799camkbdos8d290k0bfs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7YypzaSXzNXEUYhgpa9n4nV_ZpnJtG4',
    appId: '1:374997485934:ios:99ff42679def02ea4d997f',
    messagingSenderId: '374997485934',
    projectId: 'chat-app-8332b',
    storageBucket: 'chat-app-8332b.appspot.com',
    iosClientId: '374997485934-4o0cvia7ak799camkbdos8d290k0bfs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
